#!/bin/bash
set -o errexit


# Should give an arg
if [ $# == 0 ]
then
	echo "? executes the testbench for the module"
	echo "syntax:"
	echo "  ./sim-module <module-name>"
	exit
fi


# create uut work directory
test -d uut && rm -rf uut
mkdir -p uut/src

# copy verilog code files from hdl directory into uut work dir
for FILE in $(find ./hdl/* -name "*.v" -type f -print)
do
	cp -n $FILE ./uut/src/ || { echo "ERROR duplicate filename ${FILE}" ; exit 1; }
done

# copy verilog header files from hdl directory into uut work dir
for FILE in $(find ./hdl/* -name "*.vh" -type f -print)
do
	cp -n $FILE ./uut/src/ || { echo "ERROR duplicate filename ${FILE}" ; exit 1; }
done

# copy SystemVerilog code files from hdl directory into uut work dir
for FILE in $(find ./hdl/* -name "*.sv" -type f -print)
do
	cp -n $FILE ./uut/src/ || { echo "ERROR duplicate filename ${FILE}" ; exit 1; }
done

# cd into the working dir
cd uut/src

# UUT should contain the name of the unit under test
if [ -f $1_tb.v ]
then
	UUT=$1
else
	echo "syntax:"
	echo "  ./sim-module <module-name>"
	echo ""
	echo "Where <module-name>_tb.v should exist"
	exit
fi

# compile current unit
echo "UUT = $UUT"
iverilog -g2009 -o ../$UUT ${UUT}_tb.v
cd ..

# run current simul/testbench
if [ -f $UUT ]
then
	./$UUT
else
	echo "iverilog failed"
	exit
fi


echo "test for unit ${UUT} done"
